version: '3.8'

services:
  agmeal-app:
    build: .
    container_name: sgc-agmeal-web
    restart: unless-stopped
    volumes:
      # Mantém o banco de dados a salvo
      - ./data:/sgc/data
      
      # NOVO: Mantém as fotos de perfil a salvo!
      # Cria uma pasta 'uploads' no seu projeto local e liga ela à pasta do container
      - ./uploads:/sgc/app/static/uploads/fotos
    environment:
      - TZ=America/Maceio

  nginx:
    image: nginx:alpine
    container_name: sgc-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - agmeal-app